### ISSUE TITLE
ldrestart puts phone into bootloop!!!

### ISSUE THREAD

**Issue by lotharzenger** [cbyrne/Dragspring#1] opened 2020-06-17 19:34 UTC
ldrestart puts phone into bootloop!!!

**Comment by conorthedev** [comment] 2020-06-18 09:11
During my testing I've never encountered this issue. Are you using the custom command or the preset option?

**Comment by conorthedev** [comment] 2020-06-21 14:42
Closing this issue as I am unable to reproduce and original submitter hasn't responded in 4 days

**Closed as completed by conorthedev** 2020-06-21 14:42 UTC
